import React from 'react';
import { motion } from 'framer-motion';
import { Share2, Clock, BookOpen, Film } from 'lucide-react';
import type { YearlyReviewData } from '../../../lib/yearlyReview';

interface SummarySlideProps {
    data: YearlyReviewData;
}

export const SummarySlide: React.FC<SummarySlideProps> = ({ data }) => {
    // Calculat totals
    const totalMedia =
        data.media.movies.total +
        data.media.books.total +
        data.media.games.total +
        data.media.anime.total +
        data.media.tvShows.total;

    return (
        <div className="w-full h-full relative snap-start flex flex-col items-center justify-center overflow-hidden bg-slate-950 text-white">
            {/* Background Gradient */}
            <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-950 to-slate-950" />
            <div className="absolute inset-0 opacity-20 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] filter contrast-150 brightness-150" />

            <div className="relative z-10 w-full max-w-sm p-6">
                <motion.div
                    initial={{ scale: 0.9, opacity: 0 }}
                    whileInView={{ scale: 1, opacity: 1 }}
                    transition={{ duration: 0.8, type: "spring" }}
                    className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-[2rem] p-8 shadow-2xl relative overflow-hidden"
                >
                    {/* Lighting Effect */}
                    <div className="absolute top-0 right-0 w-32 h-32 bg-teal-500/20 blur-3xl rounded-full" />
                    <div className="absolute bottom-0 left-0 w-32 h-32 bg-purple-500/20 blur-3xl rounded-full" />

                    {/* Card Content */}
                    <div className="relative z-10 text-center space-y-8">
                        <div>
                            <p className="text-white/40 text-xs tracking-[0.5em] uppercase mb-4">Memory Lane</p>
                            <h2 className="text-4xl font-black bg-clip-text text-transparent bg-gradient-to-r from-teal-200 to-purple-200">
                                {data.year}
                            </h2>
                            <p className="text-white/60 text-sm mt-2">Annual Summary</p>
                        </div>

                        <div className="grid grid-cols-1 gap-6">
                            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl">
                                <div className="flex items-center space-x-3">
                                    <div className="p-2 bg-orange-500/20 rounded-lg">
                                        <Clock className="w-5 h-5 text-orange-400" />
                                    </div>
                                    <span className="text-sm text-white/60">运动时长</span>
                                </div>
                                <span className="text-xl font-bold">{data.habits.exercise.totalMinutes?.toLocaleString()} min</span>
                            </div>

                            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl">
                                <div className="flex items-center space-x-3">
                                    <div className="p-2 bg-blue-500/20 rounded-lg">
                                        <BookOpen className="w-5 h-5 text-blue-400" />
                                    </div>
                                    <span className="text-sm text-white/60">阅读页数</span>
                                </div>
                                <span className="text-xl font-bold">{data.habits.reading.totalPages?.toLocaleString()} p</span>
                            </div>

                            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl">
                                <div className="flex items-center space-x-3">
                                    <div className="p-2 bg-purple-500/20 rounded-lg">
                                        <Film className="w-5 h-5 text-purple-400" />
                                    </div>
                                    <span className="text-sm text-white/60">媒体探索</span>
                                </div>
                                <span className="text-xl font-bold">{totalMedia} items</span>
                            </div>
                        </div>

                        <div className="pt-8 border-t border-white/10">
                            <p className="text-white/80 font-serif italic text-lg">
                                "Every moment matters."
                            </p>
                            <p className="text-white/30 text-xs mt-4">Generated by Memory Lane</p>
                        </div>
                    </div>
                </motion.div>

                <motion.div
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    transition={{ delay: 1 }}
                    className="mt-8 flex justify-center"
                >
                    <button className="flex items-center space-x-2 px-6 py-3 bg-white text-black rounded-full font-bold hover:bg-white/90 active:scale-95 transition-all text-sm">
                        <Share2 className="w-4 h-4" />
                        <span>Share Memory</span>
                    </button>
                </motion.div>
            </div>
        </div>
    );
};
